new Module("Utils")
.setAuthor("Gorlem, updated by spthiel")
.setDescription("This module adds a lot of random things which don't deserve their own module.")
.addAction("&result = TRIM(%&string%)","Removes whitespace from the beginning and the end")
.addAction("SHUFFLE(array[])","Shuffles an array")
.addEvent("onDeath","Triggers when the player dies")
.addEvent("onRespawn","Triggers when the user respawns")
.addEvent("onPotionEffect","Triggers when a potioneffect is applied. Possible variables: %NEWEFFECTID% %NEWEFFECT% %NEWEFFECTNAME% %NEWEFFECTPOWER% %NEWEFFECTTIME%")
.addIterator("actions","Iterates over a list of all actions. Possible variables: %ACTIONNAME% %ACTIONUSAGE% %ACTIONRETURN% %ACTIONDESCRIPTION%")
.addIterator("events","Iterates over a list of all events. Possible variables: %EVENTNAME% %EVENTID% %EVENTHELP[]%")
.addIterator("iterators","Iterates over a list of all iterators. Possible variables: %ITERATORNAME%")
.addChangelog(26,"15/nov/19")
    .addLine("Updated to API 26")
    .build()
.addChangelog(17,null)
    .addLine("Initial release")
    .build()
.addDownload(17,"http://modules.gorlem.ml/download/0BxhkVZpaJtV3QjBZMWQ0X2NnWUE")
.addDownload(26,"https://www.dropbox.com/s/42de5v4sq2alpdg/module_utils-1.0-26.1-0.15.4-mc1.12.1.jar?dl=0");

new Module("Documentor")
.setAuthor("spthiel")
.setDescription("Let's you create custom or replace existing documentation entries for macromod")
.addAction("ADDDOCS(<name of entry>,[usage],[description],[return type])","Adds documentation to an action")
.addAction("&docs[] = LISTDOCS([name])","Returns the documentation of the action")
.addChangelog(26,"02/nov/18")
    .addLine("Initial release")
    .build()
.addDownload(26,"https://cdn.discordapp.com/attachments/505815454468800517/507896476681371658/module_documentorAPI-0.1-26.1-0.15.4-mc1.12.1.jar");

new Module("NotEnoughInformation")
.setAuthor("spthiel")
.setDescription("Adds useful functionality to existing functions, fileio, http requests, json parsing and a few fixes for macromod")
.addAction("calcyawto(<xpos>,<ypos>,<zpos>,[#yaw],[#dist],[#pitch])","Added optional Z argument for pitch calculations")
.addAction("for(#i,<start>,<end>,<step>)","Fixed - step now working")
.addAction("getslotitem(<slotid>,<&itemid>,[#stacksize],[#datavar],[&nbt])","Added optional nbt argument")
.addAction("gui(<gui>)","Fixed - now supports variables")
.addAction("showgui(<gui>)","Fixed - now supports variables")
.addAction("logto(<file>,<str>)","Altered - now supports relative and absolute paths")
.addAction("look/looks","Fixed - now supports spaces")
.addAction("placesign([line1],[line2],[line3],[line4])","Altered - removed last argument")
.addAction("&response = http([GET|POST|PUT|DELETE],<url>,[output stream],[headers])","Creates a http request")
.addAction("iffileexists(<path>,[expression if file should be create if missing])","checks if a file exists, files can start with ~ to be relative to minecraft directory")
.addAction("mkdir(<path>)","creates directory, files can start with ~ to be relative to minecraft directory")
.addAction("<&content[]> = readfile([&content[]],<path>)","Reads file into array, files can start with ~ to be relative to minecraft directory")
.addAction("writefile(<&array[]>,<path>,[append])","Writes array to file, files can start with ~ to be relative to minecraft directory")
.addAction("&array[] = getjsonasarray(<json>)","Returns json as key:value array")
.addAction("&keys[] = getjsonkeys(<json>)","Retuns a list of the keys of the json")
.addAction("&object = jsonget(<json>,<key>)","Retuns the object of the key of the specified json")
.addAction("sort([ASC,DSC],<array[]>,[array[]],...)","Sorts the arrays synchronously")
.addAction("<&members[]|&teams[]> = teammebers([team])","Lists all the members of a scoreboard team or a list of all the teamnames")
.addAction("<&score|&scores[]|&obectives[]> = score([Objectivename],[playername])","Returns score of player in objective or score of all players in objective or list of objectivenames")
.addIterator("foreach(\"players\")","[a]https://spthiel.github.io/NotEnoughInformation/[/a]")
.addIterator("foreach(\"teams\")","[a]https://spthiel.github.io/NotEnoughInformation/[/a]")
.addIterator("foreach(\"objectives\")","[a]https://spthiel.github.io/NotEnoughInformation/[/a]")
.addIterator("foreach(\"scores\")","[a]https://spthiel.github.io/NotEnoughInformation/[/a]")
.addDownload(26,"https://www.dropbox.com/s/uxp0osn392co9aw/module_NotEnoughInformation-0.9-26.1-0.15.4-mc1.12.1.jar?dl=1")
.addChangelog(26,"15/nov/19")
    .addLine("Updated")
    .build()
.addChangelog(17)
    .addLine("Initial release")
    .build();

new Module("FileIO")
.setAuthor("Astrorious")
.setDescription("FileIO is a simple Module designed to make reading and writing files easier/possible.")
.addAction("FILEEXISTS(<&path>)","Returns whether the file exists")
.addAction("MKDIR(<&path>)","Creates the directory for the path")
.addAction("WRITEFILE(<&path>,<&towrite[],[append])","Writes data to the file")
.addVariable("%MINECRAFTDIR","Path of the current minecraft directory")
.addVariable("%MACROSCONFIGDIR","Path of the current macros config directory")
.addVariable("FILESEPERATOR","Character used to split directories in paths")
.addDownload(26,"https://www.dropbox.com/s/480crujdd1qzb63/module_fileio_macrokeybind_API_26.jar?dl=1")
.addChangelog(26,"01/aug/18")
    .addLine("Initial release")
    .addLine("Added FILEEXISTS script action")
    .addLine("Added MKDIR script action")
    .addLine("Added READFILE script action")
    .addLine("Added WRITEFILE script action")
    .addLine("Added MINECRAFTDIR global variable")
    .addLine("Added MACROSCONFIGDIR global variable")
    .addLine("Added FILESEPARATOR global variable")
    .build();

new Module("WindowsNotifications")
.setAuthor("spthiel")
.setDescription("Display windows system notifications with a simple command.")
.addAction("NOTIFY([title],[message])","Creates a system tray")
.addDownload(26,"./modules/windowsnotifications/module_notifications-1.0-26.1-0.15.4-mc1.12.1.jar")
.addChangelog(26)
    .addLine("Initial release")
    .build();

new Module("GetSlotItemExtended")
.setAuthor("Seferan")
.setDescription("This module provides extended versions of GetSlotItem")

new Module("JSON")
.setAuthor("xaero_")
.setDescription("This module parses and allows you to walk JSON-encoded strings without a priori knowledge of its structure.")
.addAction("[bool] = IsBoolean(<string>,[bool])","Checks if the value is a boolean")
.addAction("[bool] = IsFloat(<string>,[bool])","Checks if the value is a float")
.addAction("[bool] = IsInteger(<string>,[bool])","Checks if the value is a integer")
.addAction("[bool] = IsJsonArray(<string>,[bool])","Checks if the value is a JSON array")
.addAction("[bool] = IsJsonObject(<string>,[bool])","Checks if the value is a JSON object")
.addAction("[bool] = IsJsonPrimitive(<string>,[bool])","Checks if the value is a JSON primitive")
.addAction("[bool] = IsNumber(<string>,[bool])","Checks if the value is a number")
.addAction("[bool] = IsString(<string>,[bool])","Checks if the value is a string")
.addAction("[&output] = jsonadd(<json>,<key>,<value>,[&output])","Adds key and value to the json")
.addAction("[&output] = jsonget(<json>,<key>,[&output])","Gets value of a key")
.addAction("[bool] = jsonhas(<json>,<key>,[bool])","Returns if the json contains the key")
.addAction("[&output] = jsonremove(<json>,<key>,[&output])","Removes a key-value-pair from the json")
.addAction("[&keys] = getjsonkeys(<json>,[&keys[]])","Returns a list of all the keys of the json")
.addAction("[&array] = getjsonasarray(<json>,[&array[]]))","Returns json as key:value array")
.addAction("[&jsonarray] = jsonarrayadd(<jsonarray>,<element>,[&jsonarray])","Adds an element to the json array")
.addAction("[&output] = jsonarrayget(<jsonarray>,<index>,[&output])","Returns the element of the jsonarray")
.addAction("[#size] = jsonarraysize(<jsonarray>,[#size])","Returns the size of the jsonarray")
.addVariable("%MODULEJSON%","Returns true if the module is installed")
.addDownload(17,"./modules/json/module_json-api17_v0.1.jar")
.addDownload(24,"./modules/json/module_json-api24_v0.1.jar")
.addDownload(26,"./modules/json/module_json-api26_v0.1.jar")
.addChangelog(26, "25/aug/17")
    .addLine("Removed beta label")
    .build()
.addChangelog(15, "28/feb/14")
    .addLine("Initial release")
    .build();

new Module("Clipboard")
.setAuthor("xaero_")
.setDescription("This module adds clipboard functions to read and write from the system clipboard.")
.addAction("GETCLIPBOARD([&text])","Returns content of clipboard")
.addAction("SETCLIPBOARD(<text>)","Sets the clipboard text")
.addVariable("MODULECLIPBOARD","Returns true if the module is installed")
.addDownload(17,"./modules/clipboard/module_clipboard-api17_v0.1.jar")
.addDownload(24,"./modules/clipboard/module_clipboard-api24_v0.1.jar")
.addDownload(26,"./modules/clipboard/module_clipboard-api26_v0.1.jar")
.addChangelog(15,"22/feb/14")
    .addLine("Initial release")
    .build();

new Module("HTTP")
.setAuthor("xaero_")
.setDescription("This module is a bastardized HTTP client that allows you to fetch web resources into your macro, or upload some data to a server.")
.addAction("[&response[]] = HTTPGET(<url>,<query>,<#status>,[&response])","Performs a httpget request to specified url")
.addAction("[&response[]] = HTTPPOST(<url>,<data>,<#status>,[&response])","Performs a httppost request to specified url with the data")
.addAction("[&response[]] = HTTPPUT(<url>,<data>,<#status>,[&response])","Performs a httpput request to specified url with the data")
.addAction("[&response[]] = HTTPDELETE(<url>,<query>,<#status>,[&response])","Performs a httpdelte request to specified url")
.addAction("[&output] = URLENCODE(<string>,[&output])","URL Encodes the string")
.addAction("SETREQUESTHEADER(<&field>,<&value>)","Sets a request header for the next request")
.addVariable("%MODULEHTTP%","Returns true if the module is installed")
.addDownload(17,"./modules/http/module_http-api17_v0.2.jar")
.addDownload(24,"./modules/http/module_http-api24_v0.2.jar")
.addDownload(26,"./modules/http/module_http-api26_v0.2.jar")
.addChangelog(26,"25/aug/17")
    .addLine("Added SETREQUESTHEADER action")
    .build()
.addChangelog(15,"22/feb/14")
    .addLine("Added MODULEHTTP environment variable")
    .build()
.addChangelog(13,"17/oct/13")
    .addLine("Initial release")
    .build();

new Module("SignText")
.setAuthor("xaero_")
.setDescription("This module allows you to retrieve the sign text from a sign you're hitting, or with absolute coordinates. Also in single player, it will allow you to change the sign text without breaking it.")
.addAction("[&outarray] = GETHITSIGNTEXT([&outarray])","Returns signtext of the sign in view")
.addAction("[&outarray] = GETSIGNTEXT(<x>,<y>,<z>,[&outarray])","Returns signtext of sign at absolute coordinates")
.addAction("SETSIGNTEXT(<x>,<y>,<z>,<line1>,<line2>,<line3>,<line4>)","In singleplayer set text of sign")
.addVariable("%MODULESIGNTEXT%","Returns true if the module is installed")
.addDownload(17,"./modules/signtext/module_signtext-api17_v0.2.2.jar")
.addDownload(24,"./modules/signtext/module_signtext-api24_v0.2.2.jar")
.addDownload(26,"./modules/signtext/module_signtext-api26_v0.2.2.jar")
.addChangelog(26,"25/aug/17")
    .addLine("Removed GETHITSIGNTEXT since it's built-in to the main mod now")
    .build()
.addChangelog(16,"01/sep/14")
    .addLine("Added MODULESIGNTEXT environment variable")
    .build()
.addChangelog(13,"17/oct/2013")
    .addLine("Array parameter is optional and is overwritten if there was a sign")
    .addLine("Text is returned for assignment")
    .addLine("Added SETSIGNTEXT for singleplayer")
    .build()
.addChangelog(12)
    .addLine("Initial release")
    .build();

new Module("FarHit")
.setAuthor("xaero_")
.setDescription("This module adds a few environmental variables that extends almost all the HIT* variables into the distance.")
.addVariable("%FARHIT%","Same as %HIT% but extended reach")
.addVariable("%FARHITID%","Same is %HITID% but extended reach")
.addVariable("%FARHITDATA%","Same as %HITDATA% but extended reach")
.addVariable("%FARHITNAME%","Same is %HITNAME% but extended reach")
.addVariable("%FARHITSIDE%","Same as %HITSIDE% but extended reach")
.addVariable("%FARHITX%","Same is %HITIX% but extended reach")
.addVariable("%FARHITY%","Same as %HITY% but extended reach")
.addVariable("%FARHITZ%","Same is %HITZ% but extended reach")
.addVariable("%FARHITUUID%","Same is %HITUUID% but extended reach")
.addVariable("%FARHITDIST%","Distance to block")
.addVariable("%MDULEFARHIT%","Distance to block")
.addDownload(17,"./modules/farhit/module_farhit-api17_v0.1.3.jar")
.addChangelog(17,"27/jan/15")
    .addLine("Preliminary update (missing HIT properties)")
    .addLine("Added FARHITUUID for players")
    .build()
.addChangelog(16,"01/sep/14")
    .addLine("Added MODULEFARHIT environment variable")
    .build()
.addChangelog(13,"17/oct/13")
    .addLine("Removed deprecated function")
    .build()
.addChangelog(12,"19/aug/13")
    .addLine("Initial release")
    .build();